### ISSUE TITLE
I have Problem With Zoom Bigger Than 14

### ISSUE THREAD

**Issue by Veria70** [delebash/unreal_map_bridge_desktop#2]
when i want to override zoom and set zoom level to 15 this error occurred 
ERROR in app: Exception on /process_tiles [POST]
Traceback (most recent call last):
  File "flask\app.py", line 2190, in wsgi_app
  File "flask\app.py", line 1486, in full_dispatch_request
  File "flask_cors\extension.py", line 176, in wrapped_function
  File "flask\app.py", line 1484, in full_dispatch_request
  File "flask\app.py", line 1469, in dispatch_request
  File "app.py", line 42, in process_tiles
  File "stitch_tiles.py", line 141, in stitch_tiles
  File "PIL\Image.py", line 2410, in save
FileNotFoundError: [Errno 2] No such file or directory: '/tile_lat_33.35140_lng_53.65153/satellite_zoom_13.png'

**Comment by delebash** [comment]
Make sure you set the Desktop directory to the same path as the Download directory in settings page of the map app.  The download directory you select by clicking the button, then use that same path for the desktop directory such as c:\myfiles.  Let me know if this fixes it.
